apiVersion: batch/v1
kind: Job
metadata:
  name: telemetrygen-metrics-gauge
  namespace: otel
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: telemetrygen
          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
          args:
            - metrics
            - --otlp-endpoint=opentelemetry-collector.otel.svc.cluster.local:4317
            - --otlp-insecure
            - --metric-type=Gauge
            - --otlp-metric-name=gen-gauge
            - --duration=50m
            - --rate=50


