# HyperDX OSS v2 - enable embedded ClickHouse for demo

global:
  storageClassName: standard

clickhouse:
  enabled: true
  config:
    users:
      appUserPassword: "password"
      otelUserPassword: "password"
      otelUserName: "otel"

  resources:
    limits:
      cpu: 800m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi

hyperdx:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 412Mi
  usageStatsEnabled: false
  useExistingConfigSecret: false
  otelExporterEndpoint: http://otel-opentelemetry-collector.otel.svc.cluster.local:4318

otel:
  enabled: false

mongodb:
  enabled: true
  persistence:
    enabled: true
    dataSize: 10Gi
  resources:
    limits:
      cpu: 300m
      memory: 412Mi
    requests:
      cpu: 100m
      memory: 128Mi
